apiVersion: v1
kind: ReplicationController
metadata:
  name: accounting-interface-service
spec:
  replicas: 1
  selector:
    name: accounting-rest-interface-rc
  template:
    metadata:
      labels:
        name: accounting-rest-interface-rc
    spec:
      containers:
      - name: accounting
        image: indigodatacloud/accounting:1.5.0-1
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        imagePullPolicy: Always
        env:
          - name: DATA_DB
            value: mysql://root:PutYourPassHere@xx.xxx.xx.xx/accounting-db
          - name: MYSQL_PASSWORD
            value: PutYourPassHere # for the non root user
          - name: ALLOWED_FOR_GET
            value: "[]"
          - name: SERVER_IAM_ID
            value:
          - name: SERVER_IAM_SECRET
            value:
          - name: DJANGO_SECRET_KEY
            value:
          - name: PROVIDERS_URL
            value: "http://indigo.cloud.plgrid.pl/cmdb/service/list"
          - name: IAM_URLS
            value: "[iam-test.indigo-datacloud.eu]"
          - name: ALLOWED_TO_POST
            value: "[]"
          - name: BANNED_FROM_POST
            value: "[]"
