apiVersion: v1
kind: Service
metadata:
  name: accounting-rest-interface
  labels:
    name: accounting-rest-interface
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: accounting-http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: accounting-https
  selector:
    name: accounting-rest-interface-rc
