apiVersion: v1
kind: ReplicationController
metadata:
  name: accounting-server-rc
spec:
  replicas: 1
  selector:
    name: accounting-server-rc
  template:
    metadata:
      labels:
        name: accounting-server-rc
    spec:
      containers:
      - name: accounting
        image: gregcorbett/apel:1.6.0-1
        imagePullPolicy: Always
        env:
          - name: DATA_DB
            value: mysql://root:PutYourPassHere@xx.xxx.xx.xx/accounting-db
          - name: MYSQL_PASSWORD
            value: PutYourPassHere # for the non root user
