apiVersion: v1
kind: ReplicationController
metadata:
  name: accounting-server-rc
spec:
  replicas: 1
  selector:
    name: accounting-server-rc
  template:
    metadata:
      labels:
        name: accounting-server-rc
    spec:
      containers:
      - name: accounting
        image: indigodatacloud/accounting:1.0.0-1
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        imagePullPolicy: Always
        env:
          - name: DATA_DB
            value: mysql://root:PutYourPassHere@xx.xxx.xx.xx/accounting-db
          - name: MYSQL_HOST
            value: 
          - name: MYSQL_PASSWORD
            value: PutYourPassHere # for the non root user
          - name: ALLOWED_FOR_GET
            value: "[]"
          - name: SERVER_IAM_ID
            value:
          - name: SERVER_IAM_SECRET
            value:
          - name: DJANGO_SECRET_KEY
            value:
